### ISSUE TITLE
Research: Elastalert configuration and running

### ISSUE THREAD

**Issue by rvadim** [rvadim/elastalert-k8s-automation#1]
DoD:
- Elastalert minimal configuration described
- Elastalert configuration with one rule and slack integration described
- What configuration we should keep in 'admin' part, what configuration we should delegate to 'user' part
- We know answer on: Can we use jinja2 templates for building configuration, or there are some issues?
- We know answer on: Can we use yaml for configuration parts or we should use another format?
At the end:
- Configuration example for 'admin' part
- Configuration example for 'user' part

**Comment by Kuyantsev-VP** [comment]
> DoD:
> 
> * Elastalert minimal configuration described
> * Elastalert configuration with one rule and slack integration described
> * What configuration we should keep in 'admin' part, what configuration we should delegate to 'user' part
> * We know answer on: Can we use jinja2 templates for building configuration, or there are some issues?
> * We know answer on: Can we use yaml for configuration parts or we should use another format?
>   At the end:
> * Configuration example for 'admin' part
> * Configuration example for 'user' part

1. _Elastalert minimal configuration described_
ElastAlert  configuration must be described in .yaml  file
**Required settings that must be specified in .yaml configuration file**:
* `es_host`: is the address of an Elasticsearch cluster where ElastAlert will store data about its state, queries run, alerts, and errors. At first place it is needed for ElastAlert itself. Each rule may have its own host address.
* `es_port`: is the port corresponding to `es_host`
* `rules_folder`: is directory with rules from which ElastAlert will load rule configuration files. It will attempt to load every .yaml file in the folder. Without any valid rules, ElastAlert will not start. ElastAlert will also load new rules, stop running missing rules, and restart modified rules as the files in this folder change.
* `run_every`: is how often ElastAlert will query Elasticsearch using rules.
* `buffer_time`: is the size of the query window, stretching backwards from the time each query is run. This value is ignored for rules where use_count_query or use_terms_query is set to true.
* `writeback_index`: is the name of the index in which ElastAlert will store data. (Must be created by scpecial script 'elastalert-create-index'
(See [more info about settings](https://elastalert.readthedocs.io/en/latest/running_elastalert.html#downloading-and-configuring))
2. _Elastalert configuration with one rule and slack integration described_
ElastAlert won't launch if there are no rules in 'rules_folder' directory and at the same time no rules specified by `--rule` launch option.
**Reuired settings for each rule**:
* `es_host`: The hostname of the Elasticsearch cluster the rule will use to query. (Required, string, no default) The environment variable ES_HOST will override this field.
* `es_port`: The port of the Elasticsearch cluster. (Required, number, no default) The environment variable ES_PORT will override this field.
* `index`: The name of the index that will be searched. Wildcards can be used here, such as: index: my-index-* which will match my-index-2014-10-05. You can also use a format string containing %Y for year, %m for month, and %d for day. To use this, you must also set use_strftime_index to true. (Required, string, no default)
* `type`: The RuleType to use. (see [Rule Types Doc](https://elastalert.readthedocs.io/en/latest/ruletypes.html#ruletypes)). Particular rule type requires its own particular settings to specify.
* `alert`: The `Alerter` type to use. `Alerter` defines the way that Elastalert uses to.. alert about events. (See [EA out of box alerts](https://elastalert.readthedocs.io/en/latest/ruletypes.html#alerts), [Creating your own alerter](https://elastalert.readthedocs.io/en/latest/recipes/adding_alerts.html)). 
**In case of Slack integration we have to specify setting below**:
* `alert: "slack"` (described above)
* `slack_webhook_url`: The webhook URL that includes your auth data and the ID of the channel (room) you want to post to. Go to the Incoming Webhooks section in your Slack account https://XXXXX.slack.com/services/new/incoming-webhook , choose the channel, click ‘Add Incoming Webhooks Integration’ and copy the resulting URL. You can use a list of URLs to send to multiple channels.
**Run ElastAlert**
* Before running EA, we must create an ElasticSearch index for ElastAlert (that will be used by `writeback_index`). It could be done by running script `elastalert-create-index` and following the instructions. The name that  you will specify for request  'New index name' must correspond to `writeback_index` setting.
* Once the index for EA, config file for EA and rules are created, we can check rules using `elastalert-test-rule --config <path-to-config-file> <path-to-.yaml-rule-file>` or just `elastalert-test-rule  <path-to-.yaml-rule-file>`.  Script will check sintax of rule and will try to use our rule for 1-day-old data in corresponding indexes. This script has different options (See [rule testing](https://elastalert.readthedocs.io/en/latest/ruletypes.html#testing))
* To start ElastAlert directly with Python: `python -m elastalert.elastalert --verbose --config <path-to-config>`
3. _What configuration we should keep in 'admin' part, what configuration we should delegate to 'user' part_
'User' of application we are working on may be a team of developers who uses some namespace in kubernetes as a platform for deploying their own application.  We also assume that team uses ElasticSearch for storing logs of their apllication.  
In this case 'user' must specify _several things_:
* Rules that defines alert-cases
* The way he wants to get alerts
* (Optional) ElasticSearch url and index that would be used by user. We use that index for quering application messages. It is optional because these settings are supposed to be set in 'admin' configuration as default values.
**_To think about: how should user specify that particular rule corresponds to particular index_**
_Admin config includes_:
* default  Elasticsearch `host`, `port` and `index` settings values for all users
* information about directory where rules are stored
* information about its system index and global settings that are defined for all rules in `rules_folder` directory.

4. _We know answer on: Can we use jinja2 templates for building configuration, or there are some issues?_
As soon as configuration files have .yaml  extension, as far as I can see there shouldn't be any problems with jinja2

5. _We know answer on: Can we use yaml for configuration parts or we should use another format?_
We are forced to do it.

6. _Configuration example for 'admin' part_
will be answered later
7.  _Configuration example for 'user' part_
will be answered later

**Comment by rvadim** [comment]
3.
> ElasticSearch url and index he use. We use that index for quering for application messages.

`ElasticSearch url` and `index` are optional and should be defaulted in admin config, due to in most cases it will be configured by administrator

**Comment by Kuyantsev-VP** [comment]
> > ElasticSearch url and index he use. We use that index for quering for application messages.
> 
> `ElasticSearch url` and `index` are optional and should be defaulted in admin config, due to in most cases it will be configured by administrator

Forgot  about assumption of we are going  to use a single instance of elasticsearch

**Comment by Kuyantsev-VP** [comment]
> > ElasticSearch url and index he use. We use that index for quering for application messages.
> 
> `ElasticSearch url` and `index` are optional and should be defaulted in admin config, due to in most cases it will be configured by administrator

Corrected.
