### ISSUE TITLE
Read configuration from configmap and secret data from Secret(env)

### ISSUE THREAD

**Issue by rvadim** [rvadim/elastalert-k8s-automation#3]
* Admin configuration will be stored in configmap in yaml
* All credentials to relay of slack tokens should be read from env(Kubernetes Secret map)
* Yaml configuration from file should have error handling and test coverage

**Comment by Kuyantsev-VP** [comment]
>Admin configuration will be stored in configmap in yaml
 
Example is ready, created pull request
>All credentials to relay of slack tokens should be read from env(Kubernetes Secret map)

Didnt resolve it yet

>Yaml configuration from file should have error handling and test coverage

About testing config. Should I test optional parameters that were not described [here](https://github.com/rvadim/elastalert-k8s-automation/issues/1)? 
I should say that we decided to use jsonschema.validate() method for testing configs. This method gives pretty clear result if something is wrong. [Example](https://stackoverflow.com/a/22231372).
I haven't understood yet if this method is acceptable for configs with optional parameters, because it might be many variants in this case, but it have some ideas.

**Comment by Kuyantsev-VP** [comment]
@dkondyrev 
This file could be extremely useful: [schema.yaml](https://github.com/Yelp/elastalert/blob/master/elastalert/schema.yaml)

**Comment by Kuyantsev-VP** [comment]
> I haven't understood yet if this method is acceptable for configs with optional parameters, because it might be many variants in this case, but it have some ideas.

The idea I mentioned is to use subschemas for optional settings. Like, if there is some optional setting X, we shall use some schema_for_X to validate it.
